image: 1drop/php-utils:7.4

stages:
  - test

test:phpstan:
  stage: test
  allow_failure: true
  script:
    - phpstan analyse --no-progress -c .config/phpstan.neon.dist --error-format=table --memory-limit 1G

test:phpcs:
  stage: test
  allow_failure: true
  script:
    - phpcs --standard=.config/phpcs.xml.dist -d memory_limit=512M

test:phpmd:
  stage: test
  allow_failure: true
  script:
    - phpmd . ansi .config/phpmd.ruleset.xml.dist --exclude cache/*

test:phpcpd:
  stage: test
  allow_failure: true
  script:
    - phpcpd --exclude cache/ .

test:phpcompat74:
  stage: test
  allow_failure: true
  script:
    - phpcs --standard=.config/phpcs-phpcompat_74.xml.dist -d memory_limit=512M

test:phpcompat80:
  stage: test
  allow_failure: true
  script:
    - phpcs --standard=.config/phpcs-phpcompat_80.xml.dist -d memory_limit=512M

test:editorconfig:
  stage: test
  image: mstruebing/editorconfig-checker:2.4.0
  allow_failure: true
  script:
    - ec -config .config/.ecrc
