#!/bin/bash

enable_installtool () {
  touch includes/ENABLE_INSTALL_TOOL
  echo "pr0game installtool enabled."
}

disable_installtool () {
  rm includes/ENABLE_INSTALL_TOOL
  echo "pr0game installtool disabled."
}

if [ $# -eq 0 ] ; then
  enable_installtool
  exit
fi

case $1 in
  on|true|enable)
    enable_installtool
    ;;
  off|false|disable)
    disable_installtool
    ;;
  *)
    echo "The parameter '${1}' is not valid, try on|true|enable or off|false|disable instead."
    ;;
esac
