UPDATE `uni1_planets`
SET
metal_mine = round((abs(Rand()*(10)+14))),
crystal_mine = round((abs(Rand()*(10)+14))),
deuterium_sintetizer = round((abs(Rand()*(10)+14))),
solar_plant = round((abs(Rand()*(10)+14))),
fusion_plant = round((abs(Rand()*(10)+14))),
robot_factory = round((abs(Rand()*(10)+14))),
nano_factory = round((abs(Rand()*(10-5+1)+3))),
hangar = round((abs(Rand()*(10)+14))),
metal_store = round((abs(Rand()*(10)))),
crystal_store = round((abs(Rand()*(10)))),
deuterium_store = round((abs(Rand()*(10)))),
laboratory = round((abs(Rand()*(10)+14))),
small_ship_cargo = round((abs(Rand()*(25000)))),
big_ship_cargo = round((abs(Rand()*(5000)))),
light_hunter = round((abs(Rand()*(80000)))),
heavy_hunter = round((abs(Rand()*(15000)))),
crusher = round((abs(Rand()*(25000)))),
battle_ship = round((abs(Rand()*(2500)))),
bomber_ship = round((abs(Rand()*(2500)))),
destructor = round((abs(Rand()*(5000)))),
dearth_star = round((abs(Rand()*(50)))),
battleship = round((abs(Rand()*(5000)))),
misil_launcher = round((abs(Rand()*(80000)))),
small_laser = round((abs(Rand()*(80000)))),
big_laser = round((abs(Rand()*(8000)))),
gauss_canyon = round((abs(Rand()*(800)))),
buster_canyon = round((abs(Rand()*(500))));


UPDATE `uni1_users`
SET
spy_tech = round((abs(Rand()*(20)+8))),
computer_tech = round((abs(Rand()*(20)+8))),
military_tech = round((abs(Rand()*(20)+8))),
defence_tech = round((abs(Rand()*(20)+8))),
shield_tech = round((abs(Rand()*(20)+8))),
energy_tech = round((abs(Rand()*(20)+8))),
hyperspace_tech = round((abs(Rand()*(20)+8))),
combustion_tech = round((abs(Rand()*(20)+8))),
impulse_motor_tech = round((abs(Rand()*(9)+5))),
hyperspace_motor_tech = round((abs(Rand()*(4)+8))),
laser_tech = 12,
ionic_tech = 5,
buster_tech = 7,
expedition_tech = round((abs(Rand()*(20-20)+20))),
metal_proc_tech = round((abs(Rand()*(20-20)+20))),
crystal_proc_tech = round((abs(Rand()*(20-20)+20))),
deuterium_proc_tech = round((abs(Rand()*(20-20)+20)));