version: '3.6'

services:
  web:
    environment:
      PHP_IDE_CONFIG: serverName=pr0game.ddev.site
      DB_HOST: db
      DB_USER: db
      DB_PASSWORD: db
      DB_NAME: db
      ADMIN_NAME: admin
      ADMIN_PASSWORD: admin
      ADMIN_MAIL: mail@example.com
